# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

great_wall = Wonder.create(name: 'Great Wall of China', location: 'China', date_built: 'between 5th B.C and 16th century', description: 'Stone-and-earth fortification created to protect the borders of the Chinese Empire from invading Mongols. Spans approximately 4,000 miles, making it the longest manmade structure.', votes: 0, img_url1: "https://www.planisware.com/sites/default/files/contenus/3746/china1.jpg", img_url2: "https://static.toiimg.com/photo/msid-73634793,width-96,height-65.cms", img_url3: "https://www.history.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTU3ODc5MDg1ODk2MjQ2NjAx/great-wall-of-china-hero.jpg", map_url: "https://cdn.britannica.com/05/19805-050-75597A75/Great-Wall-of-China-Asia-World-Heritage-1987.jpg")
christ = Wonder.create(name: 'Christ the Redeemer', location: 'Rio de Janeiro, Brazil', date_built: 'in 1931', description: 'Art Deco-style statue on top of Corcovado Mountain overlooking the entire city of Rio. The 130-ft reinforced concrete-and-soapstone statue was designed by Heitor da Silva Costa.', votes: 0, img_url1: "https://images.squarespace-cdn.com/content/v1/5a87961cbe42d637c54cab93/1553304357527-6RR0Y729RP6BL19KX7FR/ke17ZwdGBToddI8pDm48kL4WrIntsHuCODFzGytxs8sUqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKcw31z2cKmL83lZVTgYf1Shcnt0pzT4b-h8WwoQ3rX-86z0Q_QpJgDA4jmv5AtYw-J/christ-the-redemeer-guide%2B%2Brio-de-janeiro-brazil", img_url2: "https://www.pandotrip.com/wp-content/uploads/2014/06/Christ-the-Redeemer.jpg", img_url3: "https://drwyjmricaxm7.cloudfront.net/blog/wp-content/uploads/2019/03/Aerial-view-of-Christ-the-Redeemer-and-Rio-de-Janeiro-city-Brazil.jpg", map_url: "https://www.riohere.com/pictures/rio-map.jpg")
machu_picchu = Wonder.create(name: 'Machu Picchu', location: 'Peru', date_built: 'in the mid-1400s', description: 'Incan city of sparkling granite precariously perched between 2 towering Andean peaks, is thought by scholars to have been a sacred archaeological center for the nearby Incan capital of Cusco. Abandoned by its inhabitants during Spanish inquisition, the city was rediscovered by archeologist Hiram Bingham in 1911.', votes: 0, img_url1: "https://upload.wikimedia.org/wikipedia/commons/e/eb/Machu_Picchu%2C_Peru.jpg", img_url2: "https://content.api.news/v3/images/bin/0e2d42c8132a3983bd5db4db89321d4d", img_url3: "https://resize.hswstatic.com/w_1024/gif/machu-picchu-1.jpg", map_url: "https://www.intrepidtravel.com/sites/intrepid/files/styles/low-quality/public/elements/product/map/ggsa_2019.gif")
taj_mahal = Wonder.create(name: 'Taj Mahal', location: 'Agra, India', date_built: 'between 1632 and 1648', description: 'The mausoleum commissioned for the wife of Mughal Emperor Shah Jahan is considered the most perfect specimen of Muslim art in India. The white marble structure actually represents a number of architectural styles, including Persian, Islamic, Turkish and Indian.', votes: 0, img_url1: "https://thumbs-prod.si-cdn.com/E0Lm_ZfhHbqapE5Amhv-aiu8XYA=/1072x720/filters:no_upscale():focal(1471x1061:1472x1062)/https://public-media.si-cdn.com/filer/b6/30/b630b48b-7344-4661-9264-186b70531bdc/istock-478831658.jpg", img_url2: "https://images.theconversation.com/files/228805/original/file-20180723-189308-12b3agf.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=1200.0&fit=crop", img_url3: "https://img.etimg.com/thumb/width-1200,height-900,imgsize-238985,resizemode-1,msid-74667039/news/politics-and-nation/taj-mahal-closed-annual-shah-jahan-urs-not-to-be-held-in-the-wake-of-coronavirus.jpg", map_url: "https://cdn.britannica.com/45/137645-004-A0D89EC7/Taj-Mahal-Agra-India-World-Heritage-site-1983.jpg")
petra = Wonder.create(name: 'Petra', location: 'Jordan', date_built: 'in the 3rd century B.C.', description: 'Once the capital of the Nabataean empire of King Aretas IV with a number of incredible structures carved into stone, it most likely flourished between 9 B.C and 40 A.D. The members of this civilization proved to be early experts in manipulating water technology, constructing intricate tunnels and water chambers, which helped create an pseudo-oasis.', votes: 0, img_url1: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Treasury_petra_crop.jpeg/1200px-Treasury_petra_crop.jpeg", img_url2: "https://universes.art/fileadmin/_processed_/7/c/csm_00-IMG_0659-2000-750_a0c79c5a9a.jpg", img_url3: "https://s23835.pcdn.co/wp-content/uploads/2020/02/Jordan-Petra-Treasury-camel-2-1024x683.jpg", map_url: "https://cdn.britannica.com/43/19743-004-049C941C/Petra-site-Jordan-World-Heritage.jpg")
chichen = Wonder.create(name: 'Chichen Itza', location: 'Yucatan Peninsula, Mexico', date_built: 'between 600-750 A.D.', description: 'Once a powerful city, these Mayan ruins served as a political and economic hub for this ancient civilization. Its most famous ruin is a sophisticated astronomical observatory called El Caracol.', votes: 0, img_url1: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Chichen_Itza_3.jpg/1200px-Chichen_Itza_3.jpg", img_url2: "https://www.history.com/.image/t_share/MTU3ODc5MDg3NTA2NDAwNTg1/mayan-ruins-of-chichen-itza-built-by-may.jpg", img_url3: "https://www.cancunadventure.net/img/tours/chichen-itza-plus-5.jpg", map_url: "https://old.world-mysteries.com/itza_lmap.gif" )
colosseum = Wonder.create(name: 'Roman Colosseum', location: 'Rome, Italy', date_built: 'between 70-60 A.D.', description: 'Elliptical structure in use for more than 500 years sat nearly 50,000 spectators, who gathered to watch the gladiatorial events as well as other public spectacles, including battle reenactments, animal hunts and executions.', votes: 0, img_url1: "https://mymodernmet.com/wp/wp-content/uploads/2019/05/colosseum-facts-3.jpg", img_url2: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fstatic.onecms.io%2Fwp-content%2Fuploads%2Fsites%2F28%2F2017%2F02%2Finterior-rome-colosseum-italy-ARENA0217.jpg", img_url3: "https://res.klook.com/images/fl_lossy.progressive,q_65/c_fill,w_1200,h_630,f_auto/activities/vgm3jn4xf6mmsanreyjc/Colosseum,RomanForumandPalatineHillEntranceTicketinRome.jpg", map_url: "https://images.mapsofworld.com/allwonders/colosseum-location-map.jpg")

